"""user model updated

Revision ID: 0a8f8836667a
Revises: 21a69bb24dfe
Create Date: 2025-01-22 01:59:47.356149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8f8836667a'
down_revision: Union[str, None] = '21a69bb24dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('books_on_hands', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'books_on_hands')
    # ### end Alembic commands ###
